### ISSUE TITLE
Servizi on demand non avviabili.

### ISSUE THREAD

**Issue by Elvitek** [kodi-bino/plugin.video.mediasetplay#1]
Come da titolo, i servizi on demand non sono visibili ed ho fatto la prova con l'ultima puntata intera de "Le Iene".

**Comment by kodi-bino** [comment]
Uhm, molto strano, ho provato ora l'ultima puntata e la riproduco senza problemi.
Che versione di Kodi utilizzi? L'ho testato solo sulla 18 (RC1) su versioni precedenti potrebbe dare problemi... Hai modo di postare un log?

**Comment by Gythion** [comment]
> 
> 
> Uhm, molto strano, ho provato ora l'ultima puntata e la riproduco senza problemi.
> Che versione di Kodi utilizzi? L'ho testato solo sulla 18 (RC1) su versioni precedenti potrebbe dare problemi... Hai modo di postare un log?

Esatto, noi probabilmente utilizziamo la 17

**Comment by Elvitek** [comment]
[kodi.log](https://github.com/kodi-bino/plugin.video.mediasetplay/files/2680195/kodi.log)

Uso Kodi 17.6 , l'ultima ufficiale dal Play Store.

**Comment by Gythion** [comment]
https://is.gd/nhZp5b

**Comment by kodi-bino** [comment]
@Elvitek non riesco a capire il problema purtroppo dal tuo log, sembra che il link non sia riproducibile sul tuo dispositivo ma non capisco il motivo, su che sistema operativo / device gira il tutto?

@Gythion ho rilasciato una nuova release [1.0.1](https://github.com/kodi-bino/plugin.video.mediasetplay/archive/1.0.1.zip) che dovrebbe risolvere il tuo problema, fammi sapere come va…

In generale ho testato il tutto anche su Kodi 17.6 (Windows 10) e sembra funzionare senza problemi.

**Comment by Elvitek** [comment]
@kodi-bino Ho una smart box android. È della Amlogic, il M9C Max, Android 6.0.1, 2 gb di ram, api 23, 4 core, gpu arm OpenGL ES 2.0, processore AArch64 rev 4 e credo basti.  Ho installato anche la 1.0.1 ma il problema persiste.

**Comment by giofish** [comment]
@kodi-bino Anche io ho lo stesso identico problema usando Amazon Fire Stick con Kodi 17.6

**Comment by jackpallet** [comment]
Stesso problema su Kodi 18.0 RC-3 e TIMBOX (il box Android della TIM), non si riproducono i contenuti ondemand nemmeno con la versione 1.0.1
C'è bisogno forse di qualche altro addon per far funzionare i contenuti ondemand?
Questo il mio log:
https://paste.kodi.tv/zolupodasa.kodi

**Comment by kodi-bino** [comment]
Ho rilasciato una nuova versione 1.1.0 che dovrebbe risolvere i problemi su Android appoggiandosi al plugin inputstream.adactive per la riproduzione dei contenuti (il plugin deve essere abilitato prima di effettuare l'aggiornamento). Ho fatto un rapido test su di un paio di device Android e ora sembra funzionare.
