### ISSUE TITLE
Richiesta aggiunta canali

### ISSUE THREAD

**Issue by fabiocasciano** [kodi-bino/plugin.video.mediasetplay#10]
Caro sviluppatore,
per favore sarebbe tecnicamente possibile aggiungere le dirette live dei canali NOVE, Cielo, Paramount Network, Real Time, Food Network, Spike, TV8?
Grazie mille

**Comment by kodi-bino** [comment]
Mi spiace ma questi canali non fanno parte del network Mediaset pertanto non possono essere aggiunti a questa app. Sarebbe necessario, se tecnicamente fattibile, creare un'app ad hoc per questo network.
