### ISSUE TITLE
Kodi 18 e Inputstream adaptive su Android

### ISSUE THREAD

**Issue by Condottiero1** [kodi-bino/plugin.video.mediasetplay#11]
Ciao, Inputstream Adaptive non viene installato in Android. Tutto funziona bene in Windows, ma non in Android. I canali dal vivo e anche informazioni viste dopo il vivo funzionano, ma programmi come Caduta Libera non si vedono.
Ho seguito tutte le istruzioni ma Android, Kodi 18 e Inputstream Adaptive non vanno insieme. Sarebbe possibile avere un alternativa?  Grazie

**Comment by kodi-bino** [comment]
Purtroppo, che io sappia non sono disponibili alternative.
