### ISSUE TITLE
Non si avviano gli highlights di Sport Mediaset

### ISSUE THREAD

**Issue by falcorn87** [kodi-bino/plugin.video.mediasetplay#3]
Gli highlights sono elencati ma non sono riproducibili

**Comment by kodi-bino** [comment]
Ho rilasciato una nuova versione (1.1.0) che risolve dei problemi di compatibilità con Android, se stavi tentando di riprodurli su Android ora dovrebbero funzionare.
Se invece ti trovi all'estero il problema potrebbe essere dovuto a restrizioni geografiche, in qualunque caso se il problema persiste posta un log per aiutarmi con il debug.
