### ISSUE TITLE
[Request] Aggiornamenti automatici e miglioramenti

### ISSUE THREAD

**Issue by jackpallet** [kodi-bino/plugin.video.mediasetplay#4]
Grazie per la versione 1.1.0 che funziona con i video ondemand adesso.
Se possibile si possono abilitare gli aggiornamenti automatici del plugin in qualche modo? Ogni volta è necessario scaricare la nuova versione da qua.
Inoltre quando si va a recuperare un video ondemand è necessario cliccare 3 volte sul film richiesto per poterlo finalemente far partire, come entrare in 3 sottocartelle.... si possono evitare e velocizzare questi passaggi

**Comment by kodi-bino** [comment]
Ciao, è necessario inserire il plugin in un repository, io non ho modo di farlo ma so che i ragazzi di [androidaba.com](https://www.androidaba.com) l'hanno inserito, prova a vedere [qui](https://www.androidaba.com/mediaset-play-kodi-addon/).
Per il discorso dei click purtroppo non ho modo di rendere ancora più semplice la ricerca e la riproduzione dei video, ho fatto del mio meglio...
