### ISSUE TITLE
Problema canali live 1.1.1

### ISSUE THREAD

**Issue by Elvitek** [kodi-bino/plugin.video.mediasetplay#5]
Ora che si è risolto il bug dei programmi on demand con la versione 1.1.1, ora non si vedono più i canali live. Kodi 17.6

**Comment by kodi-bino** [comment]
Purtroppo i link che utilizzavo per lo stream ritornano ora 404.
Ho rilasciato una nuova release che utilizza le loro API per ottenere dei link validi, per ora funziona, speriamo che duri!
