### ISSUE TITLE
Film On Demand non avviabili.

### ISSUE THREAD

**Issue by Allev8** [kodi-bino/plugin.video.mediasetplay#6]
Come da titolo non riesco ad avviare nessun film on demand.
A volte qualcosa parte nella sezione programmi on demand ma nei film non riesco a farne partire neanche uno :(
Sono su nvidia shield, android 8.0, kodi rc2, qui sotto il log da installazione pulita dell'ultima versione dall'addon con io che provo ad aprire 5 volte il film 7 chili in 7 giorni senza esito positivo.

https://paste.kodi.tv/fagiyocewo.kodi

**Comment by kodi-bino** [comment]
Il problema dovrebbe essere risolto nella nuova release (1.2.1).
