### ISSUE TITLE
Aiuto per Mediaset Play

### ISSUE THREAD

**Issue by maxbambi** [kodi-bino/plugin.video.mediasetplay#7]
Ciao,
sto lavorando a risistemare un plugin per il sistema enigma2 (E2iplayer), nella parte che accede ai contenuti di Mediaset Play
https://gitlab.com/maxbambi/e2iplayer/blob/master/IPTVPlayer/hosts/hostmediasetplay.py
Per il fatto che il linguaggio è ancora python, ho trovato molti spunti dal tuo lavoro e da quello di phate86 e di ciò ti ringrazio.
Il mio obiettivo è di riuscire a ottenere tutte le informazioni da una sola fonte
https://feed.entertainment.tv.theplatform.eu/f/PR1GhC
e di abbandonare l'api
https://api-ott-prod-fe.mediaset.net/PROD/
Ci sono riuscito nella gestione di una sorta di EPG con replay, usando
`/mediaset-prod-all-listings?byListingTime=%interval%&byCallSign=%cs%`
Purtroppo non sono ancora riuscito a gestire in maniera efficiente la creazione dell'elenco alfabetico dei programmi.
Mi mancano le opportune chiavi della query
`mediaset-prod-all-brands?`
Ho trovato 
byTags=categoria
byCustomValue={brandId}{xxxx} 
byCustomValue={brandId}{xxxxx}, {subBrandId}{yyyyy}
byTitle= titolo (che però mi funziona solo con il titolo esatto, mentre non mi è riuscito di trovare una forma per fare una ricerca tipo 'A*' o 'A%')
e le varie aggiunte per selezionare i campi 
fields=campo1,campo2
e ordinare
sort=campo1,campo2

Non ho trovato neppure un modo efficiente per selezionare i programmi in onda da quelli non in onda, visto che per adesso tolgo sono quelli che non hanno il codice del canale nei dati
In considerazione che puoi sfruttare le informazioni che ho trovato e anche il mio codice, potresti aiutarmi?

**Comment by kodi-bino** [comment]
Ciao, non saprei proprio aiutarti. Ho realizzato il plugin partendo dal vecchio plugin di phate86 e cercando di riprodurre le chiamate API che vengono effettuate sul sito web. Altro purtroppo non saprei... mi spiace!
