### ISSUE TITLE
Alcuni programmi non partono

### ISSUE THREAD

**Issue by jackpallet** [kodi-bino/plugin.video.mediasetplay#9]
Ciao, ho notato adesso che ad esempio la serie TV Manifest in onda su Canale 5 nella sezione Programmi on Demand non parte. E' possibile risolvere questo problema? Grazie

**Comment by kodi-bino** [comment]
Purtroppo alcuni programmi sono protetti da DRM, in particolare le serie TV di cui Mediaset probabilmente acquista i diritti dall'estero. Al momento purtroppo non c'è una soluzione ma non escludo in futuro di farcela a riprodurli.

**Comment by jackpallet** [comment]
Bene, spero che prossimamente riesci a farli riprodurre in quanto i migliori programmi purtroppo non partono. Chiudo la segnalazione perchè non va considerato come un bug del plugin
